version: "3.3"

services:
  # MySQL
  jst-padi-db:
    container_name: "jst-padi-db"
    # path配下のDockerfile読み込み
    build: ./backend/mysql
    # コンテナが落ちたら再起動する
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: jst_padi
      # MYSQL_USER: root
      MYSQL_PASSWORD: user # ユーザのパスワード
      MYSQL_ROOT_PASSWORD: root # ルートパスワード
    ports:
      - "3306:3306"
    volumes:
      - ./backend/mysql/initdb.d:/docker-entrypoint-initdb.d # 定義どおりにテーブル作成
      - ./backend/mysql/conf.d:/etc/mysql/conf.d # MySQLの基本設定(文字化け対策)
      - ./backend/log/mysql:/var/log/mysql # ログの保存
    networks:
      - local-net

  # FastAPI
  jst-padi-api:
    # db起動後に立ち上げる
    links:
      - jst-padi-db
    container_name: "jst-padi-api"
    # path配下のDockerfile読み込み
    build: ./backend/api
    ports:
      - "8081:8081"
    volumes:
      - ./backend/api:/code/
    networks:
      - local-net

# コンテナ間で通信を行うためのネットワークブリッジ
networks:
  local-net:
    driver: bridge
