version: "3.3"

services:
  # MySQL
  jst-padi-db:
    container_name: "jst-padi-db"
    build: ./backend/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: jst_padi
      # MYSQL_USER: root
      MYSQL_PASSWORD: user # ユーザのパスワード
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./backend/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./backend/mysql/conf.d:/etc/mysql/conf.d
      - ./backend/log/mysql:/var/log/mysql
    networks:
      - local-net

  # FastAPI
  jst-padi-api:
    links:
      - jst-padi-db
    container_name: "jst-padi-api"
    build: ./backend/api
    ports:
      - "8081:8081"
    volumes:
      - ./backend/api:/code/
      - type: bind
        source: ./google-token
        target: /backend/token
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
